# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 00:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Product Name', max_length=20)),
                ('description', models.TextField()),
                ('sku', models.CharField(default='0000000', max_length=30)),
                ('cantidad_por_unidad', models.IntegerField(default=1)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('color', models.CharField(default='No color', max_length=20)),
                ('tamano', models.CharField(choices=[('P', 'Peque\xf1o'), ('M', 'Mediano'), ('G', 'Grande')], default='M', max_length=1)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('peso_unidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('producto_disponible', models.BooleanField(default=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_productos')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('delegacion', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=20)),
                ('pagina', models.CharField(default='Sin p\xe1gina disponible', max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_vendedores')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.Vendedor'),
        ),
    ]
