# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50)),
                ('delegacion', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion_envio', models.CharField(max_length=50)),
                ('delegacion_envio', models.CharField(max_length=20)),
                ('estado_envio', models.CharField(max_length=20)),
                ('codigo_postal_envio', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('delegacion', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=20)),
                ('pagina', models.CharField(default='Sin p\xe1gina disponible', max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_proveedores')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='vendedor',
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.Proveedor'),
        ),
    ]
