# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20170727_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_pedido', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('entregado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Cliente')),
                ('productos', models.ManyToManyField(to='landing.Producto')),
            ],
        ),
    ]
